name: kg_router
description: kapaigroup flutter app

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  flutter_layout_grid: 1.0.3
  flutter_lints: 1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: 4.0.0
  flutter_riverpod: 2.0.0-dev.9
  go_router: 3.1.0
  dio: 4.0.0
  get_it: 7.2.0
  http: ^0.13.5
  intl: 0.17.0
  iconly: ^1.0.1
  rxdart: ^0.27.3

  chewie: ^1.3.4
  video_player: ^2.4.5
  record: ^4.4.0

  # Interactive extension packages
  syncfusion_flutter_gauges: ^20.2.48
  swipeable_tile: ^2.0.0+2
  vibration: ^1.7.6
  appinio_swiper: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add all product images
    - ./assets/products/
    - ./assets/images/
    - ./assets/data/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
